path: /Users/willicon/Desktop/training #absolute path to file with images and labels
train: building_category_seed30/images #Train Images (relative to path)
val: building_category_seed30/images
#building_seed50_2025_10_30_083646/images # Validation images (relative to path)

#clases (Include all classes given in classes.txt file, in the order given there. )
names:
  0: Apartment
  1: Church
  2: Commercial
  3: Residential
  4: School
 

