train: /Users/willicon/Desktop/Saratoga Springs, Utah-selected/images
val: /Users/willicon/Desktop/Saratoga Springs, Utah-selected/images

# Classes
names:
  0: Apartment
  1: Church
  2: Commercial
  3: Residential
  4: School